name = "tiko-media-upload"
main = "src/index.ts"
compatibility_date = "2024-01-17"
account_id = "dc2b7d14a69351375cab6de9a13ddee9"

[env.production]
routes = [
  { pattern = "media.tikocdn.org/*", zone_name = "tikocdn.org" }
]

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "media"

[vars]
# Non-sensitive environment variables can go here

# Secrets should be set via wrangler secret or GitHub secrets:
# OPENAI_API_KEY - Set via: wrangler secret put OPENAI_API_KEY