[build]
  base = "."
  command = "pnpm install && pnpm build ui-docs"
  publish = "dist/apps/ui-docs"
  ignore = "bash ./scripts/ignore-build-ui-docs.sh"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
