name: Deploy Apps to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  check-triggers:
    runs-on: ubuntu-latest
    outputs:
      build-all-apps: ${{ steps.check.outputs.build-all-apps }}
      build-timer: ${{ steps.check.outputs.build-timer }}
      build-cards: ${{ steps.check.outputs.build-cards }}
      build-radio: ${{ steps.check.outputs.build-radio }}
      build-todo: ${{ steps.check.outputs.build-todo }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Check commit message for triggers
        id: check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MSG"
          
          # Default to no builds
          echo "build-timer=false" >> $GITHUB_OUTPUT
          echo "build-cards=false" >> $GITHUB_OUTPUT
          echo "build-radio=false" >> $GITHUB_OUTPUT
          echo "build-todo=false" >> $GITHUB_OUTPUT
          
          # Check for build all triggers
          if [[ "$COMMIT_MSG" == *"[build:all]"* ]] || [[ "$COMMIT_MSG" == *"[build:apps]"* ]]; then
            echo "build-timer=true" >> $GITHUB_OUTPUT
            echo "build-cards=true" >> $GITHUB_OUTPUT
            echo "build-radio=true" >> $GITHUB_OUTPUT
            echo "build-todo=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for specific app triggers
          if [[ "$COMMIT_MSG" == *"[build:timer]"* ]]; then
            echo "build-timer=true" >> $GITHUB_OUTPUT
          fi
          if [[ "$COMMIT_MSG" == *"[build:cards]"* ]]; then
            echo "build-cards=true" >> $GITHUB_OUTPUT
          fi
          if [[ "$COMMIT_MSG" == *"[build:radio]"* ]]; then
            echo "build-radio=true" >> $GITHUB_OUTPUT
          fi
          if [[ "$COMMIT_MSG" == *"[build:todo]"* ]]; then
            echo "build-todo=true" >> $GITHUB_OUTPUT
          fi

  check-environment:
    needs: check-triggers
    if: needs.check-triggers.outputs.build-timer == 'true' || needs.check-triggers.outputs.build-cards == 'true' || needs.check-triggers.outputs.build-radio == 'true' || needs.check-triggers.outputs.build-todo == 'true'
    runs-on: ubuntu-latest
    name: Check Required Environment Variables
    steps:
      - name: Check Cloudflare API Token
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ ERROR: Missing required secret CLOUDFLARE_API_TOKEN"
            echo "Please add this secret in GitHub Settings > Secrets and variables > Actions"
            exit 1
          fi
          echo "✅ CLOUDFLARE_API_TOKEN is configured"
      
      - name: Check Supabase Environment Variables
        run: |
          MISSING_VARS=""
          
          if [ -z "${{ secrets.VITE_SUPABASE_URL }}" ]; then
            MISSING_VARS="$MISSING_VARS VITE_SUPABASE_URL"
          fi
          
          if [ -z "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
            MISSING_VARS="$MISSING_VARS VITE_SUPABASE_ANON_KEY"
          fi
          
          if [ -n "$MISSING_VARS" ]; then
            echo "❌ ERROR: Missing required Supabase secrets:"
            for var in $MISSING_VARS; do
              echo "  - $var"
            done
            echo ""
            echo "Please add these secrets in GitHub Settings > Secrets and variables > Actions"
            exit 1
          fi
          
          echo "✅ Supabase environment variables are configured"
      
      - name: Check Cloudflare Project Names
        run: |
          # Note: Cloudflare Pages projects are created automatically from git
          # No additional secrets needed for project names
          echo "✅ Cloudflare Pages will use git repository structure"

  deploy-timer:
    needs: [check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-timer == 'true'
    runs-on: ubuntu-latest
    name: Deploy Timer App
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build Timer app
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/core build
          pnpm --filter=timer build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: dc2b7d14a69351375cab6de9a13ddee9
          command: pages deploy ./apps/timer/dist --project-name=tiko-timer --compatibility-date=2024-08-02

  deploy-cards:
    needs: [check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-cards == 'true'
    runs-on: ubuntu-latest
    name: Deploy Cards App
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build Cards app
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/core build
          pnpm --filter=cards build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: dc2b7d14a69351375cab6de9a13ddee9
          command: pages deploy ./apps/cards/dist --project-name=tiko-cards --compatibility-date=2024-08-02

  deploy-radio:
    needs: [check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-radio == 'true'
    runs-on: ubuntu-latest
    name: Deploy Radio App
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build Radio app
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/core build
          pnpm --filter=radio build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: dc2b7d14a69351375cab6de9a13ddee9
          command: pages deploy ./apps/radio/dist --project-name=tiko-radio --compatibility-date=2024-08-02

  deploy-todo:
    needs: [check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-todo == 'true'
    runs-on: ubuntu-latest
    name: Deploy Todo App
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build Todo app
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/core build
          pnpm --filter=todo build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: dc2b7d14a69351375cab6de9a13ddee9
          command: pages deploy ./apps/todo/dist --project-name=tiko-todo --compatibility-date=2024-08-02

  # Skip tiko app for now as it has build issues
  # deploy-tiko:
  #   needs: check-triggers
  #   if: needs.check-triggers.outputs.build-tiko == 'true'
  #   ...